### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mgnt** [brightdigit/SundialKit#13]
Please improve the documentation for this library, e.g. 

> SundialKit provides an abstraction layer + Combine affordances for Networking. Useful for either/both iOS or/and watchOS apps.

**Comment by leogdion** [comment]
Hey @mgnt take a look at #18 and the _0.2.0-documentation_ branch. I've added:
- documentation comments
- README.md guidence
- DOCC documentation

Let me know if it's understandable and fills in most of the gaps. If there's any remaining gaps please let me know.

**Comment by mgnt** [comment]
Very nice work on the documentation, Leo!
